# Generated by Django 3.0.4 on 2020-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200318_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Status',
            field=models.TextField(null=True),
        ),
    ]
