# Generated by Django 3.0.4 on 2020-03-17 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Status',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=7),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Intial_quote_amount',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Reserve_price',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
