# Generated by Django 3.0.4 on 2020-03-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20200318_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='user',
        ),
    ]
