# Generated by Django 3.0.4 on 2020-03-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200318_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Etime',
            new_name='etime',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Intial_quote_amount',
            new_name='iIntial_quote_amount',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Reserve_price',
            new_name='reserve_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Stime',
            new_name='stime',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Type',
            new_name='type',
        ),
    ]
