# Generated by Django 3.0.4 on 2020-03-18 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_property_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='intial_quote_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='reserve_price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('winner', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=7)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='no', max_length=7)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User')),
            ],
        ),
    ]
