# Generated by Django 3.0.4 on 2020-03-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20200318_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='auction_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=7),
        ),
    ]
