# Generated by Django 3.0.4 on 2020-03-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_property_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='auction_status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='closed', max_length=7),
        ),
    ]
