# Generated by Django 3.0.4 on 2020-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auctiondetails_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiondetails',
            name='card_name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='card_number',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='card_type',
            field=models.CharField(choices=[('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], default='debit_card', max_length=11),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='cvc',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='exp_date',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auctiondetails',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=7),
        ),
    ]
