# Generated by Django 3.0.4 on 2020-06-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20200615_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiondetails',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='auctiondetails',
            name='cvc',
            field=models.IntegerField(null=True),
        ),
    ]
