# Generated by Django 3.0.4 on 2020-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20200615_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiondetails',
            name='advance_amount',
            field=models.FloatField(null=True),
        ),
    ]
